replicaCount: 1

image:
  repository: starwitorg/dave-adapter
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${project.version}

app:
  context_path: ""
  update_frequency: 900000
  dave_url: http://localhost:8080/detector/save-latest-detections
  mapping:
    file: mapping.json
    content: |
      [
        {
          "observationAreaId": "9",
          "daveCountingId": "442984fa-3b79-4b85-ab8d-ebf5e07c5a42",
          "intersectionMapping": {
              "dave-meckauer-nordost" : "1",
              "dave-meckauer-nordwest" : "2",
              "dave-meckauer-sued" : "3",
              "dave-meckauer-ost" : "4",
              "5" : "",
              "6" : "",
              "7" : "",
              "8" : ""
          }
        }
      ]
  auth: 
    enabled: true
    tokenurl: https://auth.local
    clientid: dave
    username: username
    password: password  

service:
  port: 8080

analytics_db:
  url: jdbc:postgresql://localhost:5432/analytics
  username: analytics
  password: analytics

# extraEnv: |
#   - name: JAVA_TOOL_OPTIONS
#     value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5000
#   - name: LOGGING_LEVEL_ROOT
#     value: DEBUG

autoscaling:
  enabled: false