replicaCount: 1

image:
  repository: starwitorg/dave-adapter
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: ${project.version}

spring:
  security:
    oauth2:
      client:
        registration:
          daveclient:
            client_id: dave_api
            client_secret: supersecret
        provider:
          daveprovider:
            token_uri: https://uri


app:
  context_path: ""
  update_frequency: 900000
  dave_url: http://localhost:8080/detector/save-latest-detections
  mapping:
    file: mapping.json
    content: |
      [
        {
          "observationAreaId": "9",
          "daveCountingId": "339f992e-0925-4f6d-9e75-099bc520ad2c",
          "intersectionMapping": {
              "dave-meckauer-nordost" : "1",
              "dave-meckauer-nordwest" : "2",
              "dave-meckauer-sued" : "3",
              "dave-meckauer-ost" : "4",
              "5" : "",
              "6" : "",
              "7" : "",
              "8" : ""
          }
        }
      ]
  auth: 
    enabled: true

service:
  port: 8080

analytics_db:
  url: jdbc:postgresql://localhost:5432/analytics
  username: analytics
  password: analytics

# extraEnv: |
#   - name: JAVA_TOOL_OPTIONS
#     value: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5000
#   - name: LOGGING_LEVEL_ROOT
#     value: DEBUG

autoscaling:
  enabled: false