apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dave-adapter.fullname" . }}-mapping
  labels:
    {{- include "dave-adapter.labels" . | nindent 4 }}
data:
  {{ .Values.app.mapping.file }}: |
{{ .Values.app.mapping.content | indent 4 }}